package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/google/uuid"
	"github.com/hoshina-dev/papi/internal/model"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	return r.categoryService.Create(ctx, input)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uuid.UUID, input model.UpdateCategoryInput) (*model.Category, error) {
	return r.categoryService.Update(ctx, id, input)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.categoryService.Delete(ctx, id)
	return err == nil, err
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	items, err := r.categoryService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Category, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uuid.UUID) (*model.Category, error) {
	return r.categoryService.GetByID(ctx, id)
}
