package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/google/uuid"
	"github.com/hoshina-dev/papi/internal/model"
)

// CreateManufacturer is the resolver for the createManufacturer field.
func (r *mutationResolver) CreateManufacturer(ctx context.Context, input model.CreateManufacturerInput) (*model.Manufacturer, error) {
	return r.manufacturerService.Create(ctx, input)
}

// UpdateManufacturer is the resolver for the updateManufacturer field.
func (r *mutationResolver) UpdateManufacturer(ctx context.Context, id uuid.UUID, input model.UpdateManufacturerInput) (*model.Manufacturer, error) {
	return r.manufacturerService.Update(ctx, id, input)
}

// DeleteManufacturer is the resolver for the deleteManufacturer field.
func (r *mutationResolver) DeleteManufacturer(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.manufacturerService.Delete(ctx, id)
	return err == nil, err
}

// Manufacturer is the resolver for the manufacturer field.
func (r *queryResolver) Manufacturer(ctx context.Context, id uuid.UUID) (*model.Manufacturer, error) {
	return r.manufacturerService.GetByID(ctx, id)
}

// Manufacturers is the resolver for the manufacturers field.
func (r *queryResolver) Manufacturers(ctx context.Context) ([]*model.Manufacturer, error) {
	items, err := r.manufacturerService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Manufacturer, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}
