// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/google/uuid"
)

type GenerateUploadURLInput struct {
	ContentType string `json:"contentType"`
}

type Mutation struct {
}

type Optimize3DResponse struct {
	JobID  uuid.UUID `json:"jobID"`
	Status string    `json:"status"`
}

type Query struct {
}

type UploadURLResponse struct {
	UploadURL string `json:"uploadURL"`
	FileKey   string `json:"fileKey"`
}
