package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	validator "github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"github.com/hoshina-dev/papi/internal/model"
)

// CreatePartsInventory is the resolver for the createPartsInventory field.
func (r *mutationResolver) CreatePartsInventory(ctx context.Context, input model.CreatePartsInventoryInput) (*model.PartsInventory, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.partsInventoryService.Create(ctx, input)
}

// UpdatePartsInventory is the resolver for the updatePartsInventory field.
func (r *mutationResolver) UpdatePartsInventory(ctx context.Context, id uuid.UUID, input model.UpdatePartsInventoryInput) (*model.PartsInventory, error) {
	return r.partsInventoryService.Update(ctx, id, input)
}

// DeletePartsInventory is the resolver for the deletePartsInventory field.
func (r *mutationResolver) DeletePartsInventory(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.partsInventoryService.Delete(ctx, id)
	return err == nil, err
}

// PartsInventory is the resolver for the partsInventory field.
func (r *queryResolver) PartsInventory(ctx context.Context) ([]*model.PartsInventory, error) {
	items, err := r.partsInventoryService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.PartsInventory, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}

// PartsInventoryItem is the resolver for the partsInventoryItem field.
func (r *queryResolver) PartsInventoryItem(ctx context.Context, id uuid.UUID) (*model.PartsInventory, error) {
	return r.partsInventoryService.GetByID(ctx, id)
}

// PartsInventoryByPart is the resolver for the partsInventoryByPart field.
func (r *queryResolver) PartsInventoryByPart(ctx context.Context, partID uuid.UUID) ([]*model.PartsInventory, error) {
	items, err := r.partsInventoryService.GetByPartID(ctx, partID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.PartsInventory, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}
