package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	validator "github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"github.com/hoshina-dev/papi/internal/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.productService.Create(ctx, input)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uuid.UUID, input model.UpdateProductInput) (*model.Product, error) {
	return r.productService.Update(ctx, id, input)
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.productService.Delete(ctx, id)
	return err == nil, err
}

// AddProductPart is the resolver for the addProductPart field.
func (r *mutationResolver) AddProductPart(ctx context.Context, input model.AddProductPartInput) (*model.ProductPart, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.productService.AddPart(ctx, input)
}

// UpdateProductPart is the resolver for the updateProductPart field.
func (r *mutationResolver) UpdateProductPart(ctx context.Context, id uuid.UUID, input model.UpdateProductPartInput) (*model.ProductPart, error) {
	return r.productService.UpdatePart(ctx, id, input)
}

// RemoveProductPart is the resolver for the removeProductPart field.
func (r *mutationResolver) RemoveProductPart(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.productService.RemovePart(ctx, id)
	return err == nil, err
}

// Images is the resolver for the images field.
func (r *productResolver) Images(ctx context.Context, obj *model.Product) ([]string, error) {
	return []string(obj.Images), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	items, err := r.productService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Product, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	return r.productService.GetByID(ctx, id)
}

// SearchProducts is the resolver for the searchProducts field.
func (r *queryResolver) SearchProducts(ctx context.Context, name string) ([]*model.Product, error) {
	items, err := r.productService.Search(ctx, name)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Product, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
