package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	validator "github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"github.com/hoshina-dev/papi/internal/model"
)

// CreateProductInventory is the resolver for the createProductInventory field.
func (r *mutationResolver) CreateProductInventory(ctx context.Context, input model.CreateProductInventoryInput) (*model.ProductInventory, error) {
	validate := validator.New()
	if err := validate.Struct(input); err != nil {
		return nil, err
	}
	return r.productInventoryService.Create(ctx, input)
}

// UpdateProductInventory is the resolver for the updateProductInventory field.
func (r *mutationResolver) UpdateProductInventory(ctx context.Context, id uuid.UUID, input model.UpdateProductInventoryInput) (*model.ProductInventory, error) {
	return r.productInventoryService.Update(ctx, id, input)
}

// DeleteProductInventory is the resolver for the deleteProductInventory field.
func (r *mutationResolver) DeleteProductInventory(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.productInventoryService.Delete(ctx, id)
	return err == nil, err
}

// AddPartToProductInventory is the resolver for the addPartToProductInventory field.
func (r *mutationResolver) AddPartToProductInventory(ctx context.Context, productInventoryID uuid.UUID, partsInventoryID uuid.UUID) (bool, error) {
	err := r.productInventoryService.AddPartsInventory(ctx, productInventoryID, partsInventoryID)
	return err == nil, err
}

// RemovePartFromProductInventory is the resolver for the removePartFromProductInventory field.
func (r *mutationResolver) RemovePartFromProductInventory(ctx context.Context, productInventoryID uuid.UUID, partsInventoryID uuid.UUID) (bool, error) {
	err := r.productInventoryService.RemovePartsInventory(ctx, productInventoryID, partsInventoryID)
	return err == nil, err
}

// ProductInventory is the resolver for the productInventory field.
func (r *queryResolver) ProductInventory(ctx context.Context) ([]*model.ProductInventory, error) {
	items, err := r.productInventoryService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ProductInventory, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}

// ProductInventoryItem is the resolver for the productInventoryItem field.
func (r *queryResolver) ProductInventoryItem(ctx context.Context, id uuid.UUID) (*model.ProductInventory, error) {
	return r.productInventoryService.GetByID(ctx, id)
}

// ProductInventoryByProduct is the resolver for the productInventoryByProduct field.
func (r *queryResolver) ProductInventoryByProduct(ctx context.Context, productID uuid.UUID) ([]*model.ProductInventory, error) {
	items, err := r.productInventoryService.GetByProductID(ctx, productID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ProductInventory, len(items))
	for i := range items {
		result[i] = &items[i]
	}
	return result, nil
}
