package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/hoshina-dev/papi/internal/model"
)

// Optimize3d is the resolver for the optimize3D field.
func (r *mutationResolver) Optimize3d(ctx context.Context, input model.Optimize3DInput) (*Optimize3DResponse, error) {
	jobID, status, err := r.Resolver.optimizationService.Optimize3D(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("failed to start optimization job: %w", err)
	}

	return &Optimize3DResponse{
		JobID:  jobID,
		Status: status,
	}, nil
}

// GenerateUploadURL is the resolver for the generateUploadURL field.
func (r *queryResolver) GenerateUploadURL(ctx context.Context, input GenerateUploadURLInput) (*UploadURLResponse, error) {
	uploadURL, fileKey, err := r.Resolver.storageService.GenerateUploadURL(ctx, input.ContentType)
	if err != nil {
		return nil, fmt.Errorf("failed to generate upload URL: %w", err)
	}

	return &UploadURLResponse{
		UploadURL: uploadURL,
		FileKey:   fileKey,
	}, nil
}

// GetPart3DModel is the resolver for the getPart3DModel field.
func (r *queryResolver) GetPart3DModel(ctx context.Context, jobID uuid.UUID) (*model.Model3DResult, error) {
	return r.Resolver.optimizationService.GetModel3DResult(ctx, jobID)
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) GetPart3DModels(ctx context.Context, partID uuid.UUID) ([]*model.Model3DResult, error) {
	return r.Resolver.optimizationService.GetModel3DByPartID(ctx, partID)
}
func (r *queryResolver) GetProduct3DModels(ctx context.Context, productID uuid.UUID) ([]*model.Model3DResult, error) {
	return r.Resolver.optimizationService.GetModel3DByProductID(ctx, productID)
}
*/
