-- Revoke all privileges
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM papi_rw;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM papi_rw;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM papi_rw;
REVOKE USAGE ON SCHEMA public FROM papi_rw;
REVOKE CONNECT ON DATABASE postgres FROM papi_rw;

-- Drop the role
DROP ROLE IF EXISTS papi_rw;
